### ISSUE TITLE
Error while executing the project

### ISSUE THREAD

**Issue by RavishankarHassain-Inmarsat** [joshdreagan/camel-fastfile#1]
Hi Josh, 

I cloned the project and tried to execute the project using the mvn camel:run and getting the below exception

ravishankar.hassain@WIN-3PIVNRB7SAJ MINGW64 ~/dev/camel-fastfile (master)
$ mvn camel:run
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Camel Fast File Consumer 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> camel-maven-plugin:2.18.1:run (default-cli) > test-compile @ camel-fastfile >>>
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ camel-fastfile ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ camel-fastfile ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ camel-fastfile ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\Users\ravishankar.hassain\dev\camel-fastfile\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ camel-fastfile ---
[INFO] No sources to compile
[INFO]
[INFO] <<< camel-maven-plugin:2.18.1:run (default-cli) < test-compile @ camel-fastfile <<<
[INFO]
[INFO] --- camel-maven-plugin:2.18.1:run (default-cli) @ camel-fastfile ---
[INFO] Using org.apache.camel.spring.Main to initiate a CamelContext
[INFO] Starting Camel ...
Jan 09, 2017 2:41:35 PM org.springframework.context.support.ClassPathXmlApplicationContext prepareRefresh
INFO: Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@4b255ae8: startup date [Mon Jan 09 14:41:35 GMT 2017]; root of context hierarchy
Jan 09, 2017 2:41:36 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [D:\Users\ravishankar.hassain\dev\camel-fastfile\target\classes\META-INF\spring\applicationContext.xml]
Jan 09, 2017 2:41:38 PM org.apache.camel.spring.spi.BridgePropertyPlaceholderConfigurer loadProperties
INFO: Loading properties file from class path resource [org.apache.camel.examples.fastfile.properties]
Jan 09, 2017 2:41:38 PM org.apache.camel.spring.spi.BridgePropertyPlaceholderConfigurer loadProperties
INFO: Loading properties file from URL [file:${configFile}]
Jan 09, 2017 2:41:38 PM org.apache.camel.spring.spi.BridgePropertyPlaceholderConfigurer loadProperties
WARNING: Could not load properties from URL [file:${configFile}]: ${configFile} (The system cannot find the file specified)
[org.apache.camel.spring.Main.main()] INFO org.apache.camel.spring.CamelContextFactoryBean - Bridging Camel and Spring property placeholder configurer with id: bridgePropertyPlaceholder
[org.apache.camel.spring.Main.main()] INFO org.apache.camel.impl.converter.DefaultTypeConverter - Loaded 190 type converters
[org.apache.camel.spring.Main.main()] INFO org.apache.camel.spring.SpringCamelContext - Apache Camel 2.18.1 (CamelContext: camelContext) is starting
[org.apache.camel.spring.Main.main()] INFO org.apache.camel.management.ManagedManagementStrategy - JMX is enabled
[org.apache.camel.spring.Main.main()] INFO org.apache.camel.impl.DefaultRuntimeEndpointRegistry - Runtime endpoint registry is in extended mode gathering usage statistics of all incoming and outgoing endpoints (cache limit: 1000)
[org.apache.camel.spring.Main.main()] INFO org.apache.camel.spring.SpringCamelContext - StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
[org.apache.camel.spring.Main.main()] INFO org.apache.camel.spring.SpringCamelContext - Route: fileConsumerRoute started and consuming from: file://D:%5CUsers%5Cravishankar.hassain/input?delay=3000&delete=true&exclusiveReadLockStrategy=%23fileReadLockStrategy
[org.apache.camel.spring.Main.main()] INFO org.apache.camel.spring.SpringCamelContext - Skipping starting of route sftpConsumerRoute as its configured with autoStartup=false
[org.apache.camel.spring.Main.main()] INFO org.apache.camel.spring.SpringCamelContext - Skipping starting of route ftpConsumerRoute as its configured with autoStartup=false
[org.apache.camel.spring.Main.main()] INFO org.apache.camel.spring.SpringCamelContext - Total 3 routes, of which 1 are started.
[org.apache.camel.spring.Main.main()] INFO org.apache.camel.spring.SpringCamelContext - Apache Camel 2.18.1 (CamelContext: camelContext) started in 1.060 seconds
[Camel (camelContext) thread #0 - file://D:%5CUsers%5Cravishankar.hassain/input] WARN org.apache.camel.component.file.FileConsumer - Consumer Consumer[file://D:%5CUsers%5Cravishankar.hassain/input?delay=3000&delete=true&exclusiveReadLockStrategy=%23fileReadLockStrategy] failed polling endpoint: file://D:%5CUsers%5Cravishankar.hassain/input?delay=3000&delete=true&exclusiveReadLockStrategy=%23fileReadLockStrategy. Will try again at next poll. Caused by: [java.util.ServiceConfigurationError - javax.cache.spi.CachingProvider: Provider org.infinispan.jcache.embedded.JCachingProvider could not be instantiated]
java.util.ServiceConfigurationError: javax.cache.spi.CachingProvider: Provider org.infinispan.jcache.embedded.JCachingProvider could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at javax.cache.Caching$CachingProviderRegistry$1.run(Caching.java:438)
        at javax.cache.Caching$CachingProviderRegistry$1.run(Caching.java:432)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.cache.Caching$CachingProviderRegistry.getCachingProviders(Caching.java:432)
        at javax.cache.Caching$CachingProviderRegistry.getCachingProvider(Caching.java:370)
        at javax.cache.Caching$CachingProviderRegistry.getCachingProvider(Caching.java:351)
        at javax.cache.Caching.getCachingProvider(Caching.java:142)
        at org.apache.camel.component.file.strategy.CachedFileChangedExclusiveReadLockStrategy.prepareOnStartup(CachedFileChangedExclusiveReadLockStrategy.java:52)
        at org.apache.camel.component.file.strategy.GenericFileProcessStrategySupport.prepareOnStartup(GenericFileProcessStrategySupport.java:42)
        at org.apache.camel.component.file.GenericFileConsumer.poll(GenericFileConsumer.java:108)
        at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:175)
        at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:102)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/infinispan/util/logging/LogFactory
        at org.infinispan.jcache.embedded.JCachingProvider.<clinit>(JCachingProvider.java:25)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        ... 21 more
Caused by: java.lang.ClassNotFoundException: org.infinispan.util.logging.LogFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 28 more
[Camel (camelContext) thread #0 - file://D:%5CUsers%5Cravishankar.hassain/input] WARN org.apache.camel.component.file.FileConsumer - Consumer Consumer[file://D:%5CUsers%5Cravishankar.hassain/input?delay=3000&delete=true&exclusiveReadLockStrategy=%23fileReadLockStrategy] failed polling endpoint: file://D:%5CUsers%5Cravishankar.hassain/input?delay=3000&delete=true&exclusiveReadLockStrategy=%23fileReadLockStrategy. Will try again at next poll. Caused by: [java.util.ServiceConfigurationError - javax.cache.spi.CachingProvider: Provider org.infinispan.jcache.embedded.JCachingProvider could not be instantiated]
java.util.ServiceConfigurationError: javax.cache.spi.CachingProvider: Provider org.infinispan.jcache.embedded.JCachingProvider could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at javax.cache.Caching$CachingProviderRegistry$1.run(Caching.java:438)
        at javax.cache.Caching$CachingProviderRegistry$1.run(Caching.java:432)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.cache.Caching$CachingProviderRegistry.getCachingProviders(Caching.java:432)
        at javax.cache.Caching$CachingProviderRegistry.getCachingProvider(Caching.java:370)
        at javax.cache.Caching$CachingProviderRegistry.getCachingProvider(Caching.java:351)
        at javax.cache.Caching.getCachingProvider(Caching.java:142)
        at org.apache.camel.component.file.strategy.CachedFileChangedExclusiveReadLockStrategy.prepareOnStartup(CachedFileChangedExclusiveReadLockStrategy.java:52)
        at org.apache.camel.component.file.strategy.GenericFileProcessStrategySupport.prepareOnStartup(GenericFileProcessStrategySupport.java:42)
        at org.apache.camel.component.file.GenericFileConsumer.poll(GenericFileConsumer.java:108)
        at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:175)
        at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:102)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.infinispan.jcache.embedded.JCachingProvider
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        ... 21 more
[Camel (camelContext) thread #0 - file://D:%5CUsers%5Cravishankar.hassain/input] WARN org.apache.camel.component.file.FileConsumer - Consumer Consumer[file://D:%5CUsers%5Cravishankar.hassain/input?delay=3000&delete=true&exclusiveReadLockStrategy=%23fileReadLockStrategy] failed polling endpoint: file://D:%5CUsers%5Cravishankar.hassain/input?delay=3000&delete=true&exclusiveReadLockStrategy=%23fileReadLockStrategy. Will try again at next poll. Caused by: [java.util.ServiceConfigurationError - javax.cache.spi.CachingProvider: Provider org.infinispan.jcache.embedded.JCachingProvider could not be instantiated]
java.util.ServiceConfigurationError: javax.cache.spi.CachingProvider: Provider org.infinispan.jcache.embedded.JCachingProvider could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at javax.cache.Caching$CachingProviderRegistry$1.run(Caching.java:438)
        at javax.cache.Caching$CachingProviderRegistry$1.run(Caching.java:432)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.cache.Caching$CachingProviderRegistry.getCachingProviders(Caching.java:432)
        at javax.cache.Caching$CachingProviderRegistry.getCachingProvider(Caching.java:370)
        at javax.cache.Caching$CachingProviderRegistry.getCachingProvider(Caching.java:351)
        at javax.cache.Caching.getCachingProvider(Caching.java:142)
        at org.apache.camel.component.file.strategy.CachedFileChangedExclusiveReadLockStrategy.prepareOnStartup(CachedFileChangedExclusiveReadLockStrategy.java:52)
        at org.apache.camel.component.file.strategy.GenericFileProcessStrategySupport.prepareOnStartup(GenericFileProcessStrategySupport.java:42)
        at org.apache.camel.component.file.GenericFileConsumer.poll(GenericFileConsumer.java:108)
        at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:175)
        at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:102)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.infinispan.jcache.embedded.JCachingProvider
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        ... 21 more

Please let me know, if I am missing anything.

**Comment by RavishankarHassain-Inmarsat** [comment]
If I use infinispan.version as 8.2.4.Final project is getting executed properly

**Comment by joshdreagan** [comment]
Hey Ravishankar,

Thanks for giving the project a spin! Glad you were able to resolve your issues. Infinispan is only used as a very simple cache in this case (eg, no replication or distribution). So stepping down a version shouldn't hurt anything. Not sure why 8.2.5.Final wasn't working for you, but I suppose we don't have to be too concerned as long as you are up and running. Let me know if you run into any more issues.

**Comment by ravishankarhassain** [comment]
Hi Josh, 

Quick Question : Suppose, If I have 3 active instance of the same route that is running in separate docker containers of its own and all the routes are pointing to the same source SFTP server. Will this lock strategy works out of the box or do we need to tweak it a bit to support this clustered deployment.

**Comment by joshdreagan** [comment]
Unfortunately no. This readlock strategy only checks that the file is done being written by the file producer. It won't help you for making sure multiple readers don't step on eachother's toes. Luckily, there is another mechanism for that. Take a look at [https://github.com/joshdreagan/clustered-file-consumer]. The two projects could be combined to get you what you need.
